name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils


      - name: Validate Specifications
        run: count=$(find . -name '*.xml' | wc -l); find . -name '*.xml' -print0 | sort -z | xargs -0 -r xmllint --noout && echo "Validated $count xml specifications"


